"""Output writers: csv, parquet, duckdb, sql insert files.

Two APIs:
- `write_output(df, ...)` — one-shot write of a full frame (kept for callers
  that already hold the whole table in memory).
- `ChunkWriter` — streaming: open once, `write_chunk` per chunk, `close` at the
  end. Bounds memory to a single chunk so table size no longer caps generation.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

import polars as pl

from ai_data_platform.core.exceptions import GenerationError

if TYPE_CHECKING:  # pragma: no cover
    from pyarrow.parquet import ParquetWriter

SUPPORTED_FORMATS = ("csv", "parquet", "duckdb", "sql")


class ChunkWriter:
    """Incremental writer for one table. Write chunks in generation order and
    call `close` once; peak memory is bounded to a single chunk.

    All four formats are append-capable:
      parquet — a pyarrow ParquetWriter, one row group per chunk;
      csv     — header on the first chunk, rows appended after;
      duckdb  — create-or-replace on the first chunk, insert after;
      sql     — INSERT blocks appended per chunk.
    """

    def __init__(self, table: str, output_dir: str | Path, fmt: str) -> None:
        if fmt not in SUPPORTED_FORMATS:
            raise GenerationError(
                f"Unknown output format {fmt!r}.",
                hint=f"Supported: {', '.join(SUPPORTED_FORMATS)}.",
            )
        self.table = table
        self.fmt = fmt
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        self._wrote = False
        self._pq: ParquetWriter | None = None
        self._con: Any = None
        self._fh: Any = None

        if fmt == "csv":
            self.path = out / f"{table}.csv"
            self._fh = self.path.open("wb")
        elif fmt == "parquet":
            self.path = out / f"{table}.parquet"
        elif fmt == "duckdb":
            import duckdb

            self.path = out / "generated.duckdb"
            self._con = duckdb.connect(str(self.path))
        else:  # sql
            self.path = out / f"{table}.sql"
            self._fh = self.path.open("w", encoding="utf-8")
            self._fh.write("-- generated by ai-data-platform\n")
            self._fh.write(f"-- table: {table}\n")

    def write_chunk(self, df: pl.DataFrame) -> None:
        if self.fmt == "parquet":
            import pyarrow.parquet as pq

            table = df.to_arrow()
            if self._pq is None:
                self._pq = pq.ParquetWriter(
                    str(self.path),
                    table.schema,
                    compression="zstd",
                    write_statistics=True,
                )
            else:
                # keep a stable schema across chunks (e.g. large_string vs string)
                table = table.cast(self._pq.schema)
            self._pq.write_table(table)
        elif self.fmt == "csv":
            df.write_csv(self._fh, include_header=not self._wrote)
        elif self.fmt == "duckdb":
            self._con.register("df_view", df.to_arrow())
            if not self._wrote:
                self._con.execute(
                    f'create or replace table "{self.table}" as select * from df_view'
                )
            else:
                self._con.execute(f'insert into "{self.table}" select * from df_view')
            self._con.unregister("df_view")
        else:  # sql
            self._fh.write(_sql_insert_block(df, self.table))
        self._wrote = True

    def close(self) -> Path:
        if self._pq is not None:
            self._pq.close()
        if self._con is not None:
            self._con.close()
        if self._fh is not None:
            self._fh.close()
        return self.path


def write_output(df: pl.DataFrame, table: str, output_dir: str | Path, fmt: str) -> Path:
    """One-shot write of a full frame (streams via ChunkWriter under the hood)."""
    writer = ChunkWriter(table, output_dir, fmt)
    writer.write_chunk(df)
    return writer.close()


def _sql_literals(series: pl.Series) -> list[str]:
    """Per-column SQL literal list (vectorized column scan, not row iteration)."""
    if series.dtype == pl.Boolean:
        return [
            "NULL" if v is None else ("TRUE" if v else "FALSE") for v in series.to_list()
        ]
    if series.dtype.is_numeric():
        return ["NULL" if v is None else str(v) for v in series.to_list()]
    return [
        "NULL" if v is None else f"'{str(v).replace(chr(39), chr(39) * 2)}'"
        for v in series.to_list()
    ]


def _sql_value_rows(df: pl.DataFrame) -> list[str]:
    """Build parenthesized value tuples column-first (faster than iter_rows)."""
    if df.is_empty():
        return []
    col_literals = [_sql_literals(df.get_column(c)) for c in df.columns]
    return [
        "(" + ", ".join(vals) + ")"
        for vals in zip(*col_literals, strict=True)
    ]


def _sql_insert_block(df: pl.DataFrame, table: str, batch: int = 500) -> str:
    """INSERT statements for a frame (no file header — see ChunkWriter)."""
    if df.is_empty():
        return ""
    cols = ", ".join(f'"{c}"' for c in df.columns)
    value_rows = _sql_value_rows(df)
    lines: list[str] = []
    for i in range(0, len(value_rows), batch):
        chunk = value_rows[i : i + batch]
        lines.append(f'INSERT INTO "{table}" ({cols}) VALUES\n' + ",\n".join(chunk) + ";")
    return "\n".join(lines) + "\n"
