"""Output writers: csv, parquet, duckdb, sql insert files."""

from __future__ import annotations

from pathlib import Path

import polars as pl

from ai_data_platform.core.exceptions import GenerationError


def write_output(df: pl.DataFrame, table: str, output_dir: str | Path, fmt: str) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    if fmt == "csv":
        path = out / f"{table}.csv"
        df.write_csv(path)
    elif fmt == "parquet":
        path = out / f"{table}.parquet"
        df.write_parquet(path)
    elif fmt == "duckdb":
        import duckdb

        path = out / "generated.duckdb"
        with duckdb.connect(str(path)) as con:
            con.register("df_view", df.to_arrow())
            con.execute(f'create or replace table "{table}" as select * from df_view')
    elif fmt == "sql":
        path = out / f"{table}.sql"
        path.write_text(_to_sql_inserts(df, table), encoding="utf-8")
    else:
        raise GenerationError(
            f"Unknown output format {fmt!r}.",
            hint="Supported: csv, parquet, duckdb, sql.",
        )
    return path


def _sql_literal(v: object) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def _to_sql_inserts(df: pl.DataFrame, table: str, batch: int = 500) -> str:
    cols = ", ".join(f'"{c}"' for c in df.columns)
    lines = ["-- generated by ai-data-platform", f"-- table: {table}"]
    rows = df.iter_rows()
    buf: list[str] = []
    for row in rows:
        buf.append("(" + ", ".join(_sql_literal(v) for v in row) + ")")
        if len(buf) >= batch:
            lines.append(f'INSERT INTO "{table}" ({cols}) VALUES\n' + ",\n".join(buf) + ";")
            buf = []
    if buf:
        lines.append(f'INSERT INTO "{table}" ({cols}) VALUES\n' + ",\n".join(buf) + ";")
    return "\n".join(lines) + "\n"
