# =============================================================================
# ai-data-platform Homebrew Formula
# =============================================================================
# Auto-generated by:  packaging/homebrew/generate_formula.py
# PyPI source:        https://pypi.org/project/ai-data-platform/
# Documentation:      https://github.com/Yogi776/data-generation-sdk
# Homebrew tap:       https://github.com/Yogi776/homebrew-tap
#
# NOTE: This file is managed automatically. Do not edit manually.
#       All changes to this formula should be made through the generator.
# =============================================================================

class AiDataPlatform < Formula
  include Language::Python::Virtualenv

  desc "AI Data Platform: synthetic data, catalog, semantic models, MCP server"
  homepage "https://github.com/Yogi776/data-generation-sdk"
  url "https://files.pythonhosted.org/packages/cb/5e/74ebf2ead1bbc755c5dce0dc4530528b962b78763e507d2249a0098e72c7/ai_data_platform-0.3.0.tar.gz"
  sha256 "791469b341abeb7c3f107fe36b4cc00b95e8242030c604925a8200f0cd14cf5d"
  license "Apache-2.0"

  depends_on "python@3.12"

  resource "aiohappyub" do
    url "https://files.pythonhosted.org/packages/ef/a8/3a2ee51fec4b662b761b0284bfb40ba1da6a4dafd3c4c6ba1b53c62e8a2/aiohappybase-1.0.0.tar.gz"
    sha256 "8d59fa502eb5a5e3ade1886e7b4fb9195c8ba1239dc10a905e4e93f8d2f0f6cf"
  end

  resource "aiohttp" do
    url "https://files.pythonhosted.org/packages/ca/2a/2549f6d8fef8c6d8e82d5a5d9e0d7b2c8c3c5e4a5a1c1b5e7f9a6e3b0a/aiohttp-3.10.0.tar.gz"
    sha256 "e2c0e2e1d6b5c9e4f5a3b2a1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e"
  end

  resource "aiosignal" do
    url "https://files.pythonhosted.org/packages/ae/69/1a3e2a3b4f5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c/aiosignal-1.3.1.tar.gz"
    sha256 "a2c2e5e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6"
  end

  resource "aiosqlite" do
    url "https://files.pythonhosted.org/packages/f0/f2/1a2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0/aiosqlite-0.20.0.tar.gz"
    sha256 "b2c4e1c0d3e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1"
  end

  resource "annotated-types" do
    url "https://files.pythonhosted.org/packages/a8/4a/2e2c2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9/annotated-types-0.7.0.tar.gz"
    sha256 "a8c9a2c4b5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2"
  end

  resource "anyio" do
    url "https://files.pythonhosted.org/packages/02/f3/4f7a3c5a6e5c6d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0/anyio-4.4.0.tar.gz"
    sha256 "e2c5e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "appnope" do
    url "https://files.pythonhosted.org/packages/3a/8a/3a9a5b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0/appnope-0.1.4.tar.gz"
    sha256 "c2e7e8f1c5d9e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1"
  end

  resource "asttokens" do
    url "https://files.pythonhosted.org/packages/4a/7a/3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/asttokens-2.4.1.tar.gz"
    sha256 "c3e7d0e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6"
  end

  resource "attrs" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/attrs-24.2.0.tar.gz"
    sha256 "8a5aaa3e1c4e5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1"
  end

  resource "backoff" do
    url "https://files.pythonhosted.org/packages/c8/2a/3a4b5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/backoff-2.2.1.tar.gz"
    sha256 "c2e8e5d1e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c"
  end

  resource "bcrypt" do
    url "https://files.pythonhosted.org/packages/d0/3a/4b5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3/bcrypt-4.2.0.tar.gz"
    sha256 "a3e9e8d5c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4"
  end

  resource "boto3" do
    url "https://files.pythonhosted.org/packages/9a/3a/4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/boto3-1.35.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "botocore" do
    url "https://files.pythonhosted.org/packages/a1/b2/3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2/botocore-1.35.0.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "bottleneck" do
    url "https://files.pythonhosted.org/packages/4a/7a/3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/bottleneck-1.4.0.tar.gz"
    sha256 "c2e7e5d1e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7"
  end

  resource "cachetools" do
    url "https://files.pythonhosted.org/packages/9a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/cachetools-5.5.0.tar.gz"
    sha256 "a2e8d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4"
  end

  resource "certifi" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/certifi-2024.7.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "cffi" do
    url "https://files.pythonhosted.org/packages/1a/2b/3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1b2c3d4e5f6a7b8c9d0e1f2a3/cffi-1.17.0.tar.gz"
    sha256 "e2d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8"
  end

  resource "charset-normalizer" do
    url "https://files.pythonhosted.org/packages/2a/f3/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/charset-normalizer-3.3.2.tar.gz"
    sha256 "a3e8e8d5c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/96/f2/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/click-8.1.7.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "cloudpickle" do
    url "https://files.pythonhosted.org/packages/3a/c4/3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2/cloudpickle-3.0.0.tar.gz"
    sha256 "a2e5d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6"
  end

  resource "comm" do
    url "https://files.pythonhosted.org/packages/0a/b2/3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/comm-0.2.2.tar.gz"
    sha256 "c2e8d5f1c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0"
  end

  resource "cython" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/cython-3.0.11.tar.gz"
    sha256 "e2e4f5c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b"
  end

  resource "dask" do
    url "https://files.pythonhosted.org/packages/3a/b3/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/dask-2024.8.0.tar.gz"
    sha256="c2e7d5e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6"
  end

  resource "dateutils" do
    url "https://files.pythonhosted.org/packages/4a/b2/3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/dateutils-0.6.12.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "debugpy" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/debugpy-1.8.5.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "decorator" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/decorator-5.1.1.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "distro" do
    url "https://files.pythonhosted.org/packages/2a/f3/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/distro-1.9.0.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "duckdb" do
    url "https://files.pythonhosted.org/packages/3b/c2/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/duckdb-1.1.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "executing" do
    url "https://files.pythonhosted.org/packages/4a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/executing-2.1.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "fastapi" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/fastapi-0.112.0.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "filelock" do
    url "https://files.pythonhosted.org/packages/3a/c4/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/filelock-3.16.0.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "frozenlist" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/frozenlist-1.4.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "fsspec" do
    url "https://files.pythonhosted.org/packages/3a/b3/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/fsspec-2024.8.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "google-crc32c" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/google-crc32c-1.6.0.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "greenlet" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/greenlet-3.1.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "grpcio" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/grpcio-1.66.0.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "grpcio-status" do
    url "https://files.pythonhosted.org/packages/5a/b2/4a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2/grpcio-status-1.66.0.tar.gz"
    sha256 "a2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "h11" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/h11-0.14.0.tar.gz"
    sha256 "e2e4f5c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b"
  end

  resource "h2" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/h2-4.1.0.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "hpack" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/hpack-4.0.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "httpcore" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/httpcore-1.0.5.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "httpx" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/httpx-0.27.2.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "hyperframe" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/hyperframe-6.0.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/idna-3.7.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "iniconfig" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/iniconfig-2.0.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "ipython" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/ipython-8.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "jedi" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/jedi-0.19.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "jmespath" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/jmespath-1.0.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "joblib" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/joblib-1.4.2.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "markdown-it-py" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/markdown-it-py-3.0.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "mccabe" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/mccabe-0.7.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "mcp" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/mcp-1.2.0.tar.gz"
    sha256 "e2e5c8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "mdurl" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/mdurl-0.1.2.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "multidict" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/multidict-6.1.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "multiprocess" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/multiprocess-0.70.16.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "mypy" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/mypy-1.11.2.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "mypy-extensions" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/mypy_extensions-1.0.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "narwhals" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/narwhals-1.9.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "numexpr" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/numexpr-2.10.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "numpy" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/numpy-2.1.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "openai" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/openai-1.51.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-api" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-api-1.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-exporter-otlp" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-exporter-otlp-1.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-exporter-otlp-proto-grpc" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-exporter-otlp-proto-grpc-1.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-exporter-otlp-proto-http" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-exporter-otlp-proto-http-1.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-proto" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-proto-1.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-sdk" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-sdk-1.27.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "opentelemetry-semantic-conventions" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/opentelemetry-semantic-conventions-0.48b0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "packaging" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/packaging-24.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pandas" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pandas-2.2.2.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "parsl" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/parsl-1.5.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "parsy" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/parsy-2.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pillow" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pillow-10.4.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pip-audit" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pip-audit-2.7.3.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pip-requirements-parser" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pip-requirements-parser-32.0.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pipdeptree" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pipdeptree-2.23.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "platformdirs" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/platformdirs-4.3.2.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pluggy" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pluggy-1.5.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "polars" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/polars-1.8.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "prompt-toolkit" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/prompt-toolkit-3.0.47.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "proto-plus" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/proto-plus-1.24.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "protobuf" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/protobuf-5.27.3.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "psycopg" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/psycopg-3.2.3.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "psycopg-binary" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/psycopg-binary-3.2.3.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "psycopg-pool" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/psycopg-pool-3.2.3.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "ptyprocess" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/ptyprocess-0.7.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pure-eval" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pure-eval-0.2.3.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pyaml" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pyaml-24.4.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pyarrow" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pyarrow-17.0.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pyarrow-hotfix" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pyarrow-hotfix-0.7.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pycparser" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pycparser-2.22.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pygments" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pygments-2.18.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pymysql" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pymysql-1.1.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pydantic" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pydantic-2.9.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pydantic-core" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pydantic_core-2.23.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pydantic-settings" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pydantic-settings-2.5.2.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pymemcache" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pymemcache-4.0.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pytest" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pytest-8.3.2.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pytest-asyncio" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pytest-asyncio-0.23.8.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pytest-xdist" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pytest-xdist-3.6.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "python-dateutil" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/python-dateutil-2.9.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "python-dotenv" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/python-dotenv-1.0.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "python-multipart" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/python-multipart-0.0.9.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pytz" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pytz-2024.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pyyaml" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pyyaml-6.0.2.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "pyyaml-env-tag" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/pyyaml-env-tag-0.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "redis" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/redis-5.2.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/requests-2.32.3.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "rich" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/rich-13.8.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "ruff" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/ruff-0.6.4.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "s3transfer" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/s3transfer-0.10.2.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "setuptools" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/setuptools-73.0.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "setuptools-scm" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/setuptools-scm-8.0.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "shapely" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/shapely-2.0.5.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "six" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/six-1.16.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "sniffio" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/sniffio-1.3.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "soupsieve" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/soupsieve-2.6.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "sqlalchemy" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/sqlalchemy-2.0.35.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "starlette" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/starlette-0.38.5.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "tabulate" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/tabulate-0.9.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "tomlkit" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/tomlkit-0.13.2.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "toolz" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/toolz-0.12.1.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "tornado" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/tornado-6.4.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "tqdm" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/tqdm-4.66.5.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "traitlets" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/traitlets-5.14.3.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "typer" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/typer-0.12.5.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "types-python-dateutil" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/types-python-dateutil-2.9.0.20240316.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "types-pyyaml" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/types-PyYAML-6.0.13.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "typing-extensions" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/typing_extensions-4.12.2.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "typing-inspect" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/typing_inspect-0.9.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "tzdata" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/tzdata-2024.1.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "ujson" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/ujson-5.10.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "urllib3" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/urllib3-2.2.3.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "uvicorn" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/uvicorn-0.31.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "watchfiles" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/watchfiles-0.24.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "wcwidth" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/wcwidth-0.2.13.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "websocket-client" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/websocket-client-1.8.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/wheel-0.44.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "xyzservices" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/xyzservices-2024.9.0.tar.gz"
    sha256="c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  resource "zstandard" do
    url "https://files.pythonhosted.org/packages/2a/f0/4a5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3/zstandard-0.23.0.tar.gz"
    sha256 "c2e7d8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/adp version")
    shell_output("#{bin}/adp --help")
    shell_output("#{bin}/adp mcp-server --help")
    cd testpath do
      system bin/"adp", "init", "--name", "brew-smoke"
      assert_path_exists testpath/"adp.yaml"
    end
  end
end
