"""Data dictionary generator: catalog -> Markdown."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from ai_data_platform.metadata.catalog import Catalog


def generate_docs(catalog: Catalog, project_name: str = "project") -> str:
    """Render a Markdown data dictionary with profiles and relationships."""
    tables = catalog.list_tables()
    rels = catalog.get_relationships()
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Data Dictionary — {project_name}",
        "",
        f"_Generated by ai-data-platform on {ts}._",
        "",
        f"**{len(tables)} table(s), {len(rels)} relationship(s).**",
        "",
    ]
    for t in tables:
        meta = catalog.get_table(t["table"])
        profile = catalog.get_latest_profile(t["table"]) or {}
        col_profiles = {c["name"]: c for c in profile.get("columns", [])}
        lines += [
            f"## {meta['table']}",
            "",
            f"- Source: `{meta['source']}` · Kind: {meta['kind']} · "
            f"Rows: {meta['row_count'] if meta['row_count'] is not None else 'unknown'}",
        ]
        if meta["description"]:
            lines += ["", meta["description"]]
        lines += [
            "",
            "| Column | Type | Nullable | PK | PII | Nulls | Distinct | Range |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for c in meta["columns"]:
            p = col_profiles.get(c["name"], {})
            rng = ""
            if p.get("min") is not None and p.get("max") is not None:
                rng = f"{p['min']} … {p['max']}"
            lines.append(
                f"| {c['name']} | {c['type']} | {'yes' if c['nullable'] else 'no'} "
                f"| {'✓' if c['primary_key'] else ''} "
                f"| {c['pii'] if c['pii'] != 'none' else ''} "
                f"| {p.get('null_ratio', '')} | {p.get('distinct', '')} | {rng} |"
            )
        lines.append("")

    if rels:
        lines += [
            "## Relationships",
            "",
            "| Child | Parent | Confidence | Provenance |",
            "|---|---|---|---|",
        ]
        for r in rels:
            lines.append(
                f"| {r['child_table']}.{r['child_column']} "
                f"| {r['parent_table']}.{r['parent_column']} "
                f"| {r['confidence']:.2f} | {r['provenance']} |"
            )
        lines.append("")
    return "\n".join(lines)
